# Site settings
title: British Airways Sale
description: >
  British Airways is set to make your long haul dreams come true this September with an enviable sale on routes to inspiring destinations.
baseurl: "/britishairwayssale" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md, npm-debug.log]

campaign-link: https://ad.doubleclick.net/ddm/clk/404152169;204368959;n?https://www.britishairways.com/en-gb/offers/sale?DM1_Channel=&DM1_Campaign=UKI_GB_EN_Secretescapes_SecretEscapes_SeptemberSale2017_Microsite&DM1_Site=Secretescapes&utm_source=Secretescapes&utm_medium=Affiliate&utm_campaign=UKI_GB_EN_Secretescapes_SecretEscapes_SeptemberSale2017_Microsite